[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_movies = "7EZkj1Y7frBDwRH5g72xqaYhLBRRH6b9vRkgLHSJA9bq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chrisjgr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
